name: jitter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  video_player: ^0.10.11+2
  animations: ^1.1.2
  loading: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/home/invalid_name.png
      - assets/images/home/drawable-hdpi/invalid_name.png
      - assets/images/home/drawable-mdpi/invalid_name.png
      - assets/images/home/drawable-xhdpi/invalid_name.png
      - assets/images/home/drawable-xxhdpi/invalid_name.png
      - assets/images/home/drawable-xxxhdpi/invalid_name.png

      - assets/images/home_active/invalid_name.png
      - assets/images/home_active/drawable-hdpi/invalid_name.png
      - assets/images/home_active/drawable-mdpi/invalid_name.png
      - assets/images/home_active/drawable-xhdpi/invalid_name.png
      - assets/images/home_active/drawable-xxhdpi/invalid_name.png
      - assets/images/home_active/drawable-xxxhdpi/invalid_name.png

      # 社区
      - assets/images/community/invalid_name.png
      - assets/images/community/drawable-hdpi/invalid_name.png
      - assets/images/community/drawable-mdpi/invalid_name.png
      - assets/images/community/drawable-xhdpi/invalid_name.png
      - assets/images/community/drawable-xxhdpi/invalid_name.png
      - assets/images/community/drawable-xxxhdpi/invalid_name.png


      - assets/images/community_active/invalid_name.png
      - assets/images/community_active/drawable-hdpi/invalid_name.png
      - assets/images/community_active/drawable-mdpi/invalid_name.png
      - assets/images/community_active/drawable-xhdpi/invalid_name.png
      - assets/images/community_active/drawable-xxhdpi/invalid_name.png
      - assets/images/community_active/drawable-xxxhdpi/invalid_name.png
      # 相机
      - assets/images/camera/invalid_name.png
      - assets/images/camera/drawable-hdpi/invalid_name.png
      - assets/images/camera/drawable-mdpi/invalid_name.png
      - assets/images/camera/drawable-xhdpi/invalid_name.png
      - assets/images/camera/drawable-xxhdpi/invalid_name.png
      - assets/images/camera/drawable-xxxhdpi/invalid_name.png

      # 任务
      - assets/images/task/invalid_name.png
      - assets/images/task/drawable-hdpi/invalid_name.png
      - assets/images/task/drawable-mdpi/invalid_name.png
      - assets/images/task/drawable-xhdpi/invalid_name.png
      - assets/images/task/drawable-xxhdpi/invalid_name.png
      - assets/images/task/drawable-xxxhdpi/invalid_name.png

      - assets/images/task_active/invalid_name.png
      - assets/images/task_active/drawable-hdpi/invalid_name.png
      - assets/images/task_active/drawable-mdpi/invalid_name.png
      - assets/images/task_active/drawable-xhdpi/invalid_name.png
      - assets/images/task_active/drawable-xxhdpi/invalid_name.png
      - assets/images/task_active/drawable-xxxhdpi/invalid_name.png

      # 我的
      - assets/images/my/invalid_name.png
      - assets/images/my/drawable-hdpi/invalid_name.png
      - assets/images/my/drawable-mdpi/invalid_name.png
      - assets/images/my/drawable-xhdpi/invalid_name.png
      - assets/images/my/drawable-xxhdpi/invalid_name.png
      - assets/images/my/drawable-xxxhdpi/invalid_name.png

      - assets/images/my_active/invalid_name.png
      - assets/images/my_active/drawable-hdpi/invalid_name.png
      - assets/images/my_active/drawable-mdpi/invalid_name.png
      - assets/images/my_active/drawable-xhdpi/invalid_name.png
      - assets/images/my_active/drawable-xxhdpi/invalid_name.png
      - assets/images/my_active/drawable-xxxhdpi/invalid_name.png

      # 爱心
      - assets/images/love/invalid_name.png
      - assets/images/love/drawable-hdpi/invalid_name.png
      - assets/images/love/drawable-mdpi/invalid_name.png
      - assets/images/love/drawable-xhdpi/invalid_name.png
      - assets/images/love/drawable-xxhdpi/invalid_name.png
      - assets/images/love/drawable-xxxhdpi/invalid_name.png

      - assets/images/love_active/invalid_name.png
      - assets/images/love_active/drawable-hdpi/invalid_name.png
      - assets/images/love_active/drawable-mdpi/invalid_name.png
      - assets/images/love_active/drawable-xhdpi/invalid_name.png
      - assets/images/love_active/drawable-xxhdpi/invalid_name.png
      - assets/images/love_active/drawable-xxxhdpi/invalid_name.png

      - assets/images/love_white/invalid_name.png
      - assets/images/love_white/drawable-hdpi/invalid_name.png
      - assets/images/love_white/drawable-mdpi/invalid_name.png
      - assets/images/love_white/drawable-xhdpi/invalid_name.png
      - assets/images/love_white/drawable-xxhdpi/invalid_name.png
      - assets/images/love_white/drawable-xxxhdpi/invalid_name.png

      # 消息
      - assets/images/information/invalid_name.png
      - assets/images/information/drawable-hdpi/invalid_name.png
      - assets/images/information/drawable-mdpi/invalid_name.png
      - assets/images/information/drawable-xhdpi/invalid_name.png
      - assets/images/information/drawable-xxhdpi/invalid_name.png
      - assets/images/information/drawable-xxxhdpi/invalid_name.png


    # 分享
      - assets/images/share/invalid_name.png
      - assets/images/share/drawable-hdpi/invalid_name.png
      - assets/images/share/drawable-mdpi/invalid_name.png
      - assets/images/share/drawable-xhdpi/invalid_name.png
      - assets/images/share/drawable-xxhdpi/invalid_name.png
      - assets/images/share/drawable-xxxhdpi/invalid_name.png
      

  #   - assets/svgs/home.svg
  #   - assets/svgs/home_active.svg
  #   - assets/svgs/community.svg
  #   - assets/svgs/community_active.svg
  #   - assets/svgs/camera.svg
  #   - assets/svgs/task.svg
  #   - assets/svgs/task_active.svg
  #   - assets/svgs/my.svg
  #   - assets/svgs/my_active.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
