/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData camera = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData community = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData community_active = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg, matchTextDirection: true);
  static const IconData home_active = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_active = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task_active = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
